name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install build-essential and libss-dev
      run: apt-get update && apt-get install build-essential libssl-dev pkg-config -y
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose